server:
  port: ${PORT:${SERVER_PORT:0}}

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: catalog-service
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      database: test
      port: 27031
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672


queue:
  movie:
    name: MovieQueue
  serie:
    name: SerieQueue

message: hello catalog

management:
  endpoints:
    web:
      exposure:
        include: circuitbreakers,circuitbreakerevents,health,info,ratelimiters,metrics
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      serie:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  retry:
    instances:
      serie:
        maxAttempts: 3
        waitDuration: 1000
        retryExceptions:
          - feign.FeignException$InternalServerError


info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: Catalog Microservice
  svc:
    intanceid: ${eureka.instance.instance-id}
    port: ${server.port}




#server:
#  port: ${PORT:${SERVER_PORT:0}}
#
#idRandom: ${random.value}
#
#eureka:
#  instance:
#    hostname: catalog-service
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#  client:
#    service-url:
#      defaultZone: http://eurekaserver:8761/eureka
#
#spring:
#  application:
#    name: catalog-service
#  mongodb:
#    embedded:
#      version: 4.0.2
#  data:
#    mongodb:
#      database: test
#      port: 27031
#  rabbitmq:
#    username: guest
#    password: guest
#    host: rabbitmq3
#    port: 5672
#
#  zipkin:
#    base-url: http://zipkin:9411
#    enabled: true
#
#queue:
#  movie:
#    name: MovieQueue
#  serie:
#    name: SerieQueue
#
#message: hello catalog
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: info
#  info:
#    env:
#      enabled: true
#  endpoint:
#    info:
#      enabled: true
#
#info:
#  app:
#    name: ${spring.application.name}
#    version: 1.0.0
#    description: Catalog Microservice
#  svc:
#    intanceid: ${eureka.instance.instance-id}
#    port: ${server.port}