server:
  port: ${PORT:8761}

spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://zipkin:9411
    enabled: true
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#    server:
#      port: ${PORT:8761}
#
#    spring:
#      application:
#        name: eureka-server
#      zipkin:
#        base-url: http://zipkin:9411
#        enabled: true
#    eureka:
#      instance:
#        hostname: localhost
#      client:
#        registerWithEureka: false
#        fetchRegistry: false
#        serviceUrl:
#          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/